baseURL = "https://tourcoder.com/"
languageCode = "en-us"

title = "代码旅行"
copyright = "TOURCODER.COM"

theme = "tchugo"

publishDir = "public"
disableKinds = ["taxonomy", "term"]

[pagination]
  pagerSize = 9

[params]
  author = "Bin HUA" #replace with your name
  lazyImage = true
  slogan = "信仰永恒，无所畏惧|Do Faith No Fear"
  description = "代码旅行是我的个人博客，它集合了我的学习笔记，播客以及视频的内容。分享我的所学，所思，所想，所玩。信仰永恒，无所畏惧|Do Faith No Fear"
  keywords = "代码旅行, tourcoder, 代码, 旅行, 推特, twitter, 播客, podcast, 博客, blog, blogger, youtube, github, 开源, opensource, 信仰永恒，无所畏惧, Do Faith No Fear"
  logo = "/imgs/logo.jpg"
  home_image = "/imgs/about.webp"
  bio = "这是一位热爱分享、动手能力强、注重效率且有着丰富实战经验的博主。这个博客更像是他的一本公开的“技术错题本”、“经验备忘录”和“人生记录簿”。<br />这个博主崇尚「饿了就吃，困了就睡，累了就放弃」，生活相对自由散漫了点，全球不定期刷新的 NPC。"
  # 开启本地搜索
  fastSearch = true
  home_project_limit = 20
  home_blog_limit = 22

[params.social]
  xcoder  = "https://xcoder.org/@tourcoder"
  x       = "https://x.com/tourcoder"
  github  = "https://github.com/tourcoder"
  youtube = "https://www.youtube.com/@tourcoder"
  email   = "code@tourcoder.com"

[permalinks]
  blog = "/:slug"
  extend = "/:slug"
  projects = "/:slug"
  
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe = true

[blackfriday]
  taskLists = true
  angledQuotes = true
  fractions = true
  plainIDAnchors = true
  tabSizeDefault = 4
  extensions = ["hardLineBreak", "tables", "noEmptyLineBeforeBlock", "definitionLists"]

[frontmatter]
  lastmod = ['lastmod', ':git', ':fileModTime', 'date', 'publishDate']

[outputs]
  home = ["HTML", "RSS", "JSON"]

